{{- if .Values.scaling.enabled }}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: {{ include "diet-optimizer.fullname" . }}
  labels:
    {{- include "diet-optimizer.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "diet-optimizer.fullname" . }}-internal.{{ .Release.Namespace }}.svc.cluster.local
  scaleTargetRef:
    name: {{ include "diet-optimizer.fullname" . }}
    kind: Deployment
    apiVersion: apps/v1
    service: {{ include "diet-optimizer.fullname" . }}-internal
    port: {{ .Values.service.port }}
  replicas:
    min: {{ .Values.scaling.minReplicas }}
    max: {{ .Values.scaling.maxReplicas }}
  scaledownPeriod: {{ .Values.scaling.scaledownPeriod }}
  scalingMetric:
    requestRate:
      targetValue: {{ .Values.scaling.targetRequestRate }}
      window: {{ .Values.scaling.window }}
{{- end }}
